name: Python Deployment

on:
  push:
    branches:
      - master  # Runs the workflow when you push to 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change version if needed

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest  # Runs unit tests if you have any

      - name: Deploy to Server (Example)
        env:
          SERVER_IP: ${{ secret_ip }}
          SSH_PRIVATE_KEY: ${{ secret_pem_key }}
        run: |
          echo "$SSH_PRIVATE_KEY" > secret_ip
          chmod 600 secret_pem_key
          ssh -i secret_pem_key ubuntu@secret_ip "cd /your-app && git pull origin main && systemctl restart your-app"
